backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/site.json"
        label: "Main"
        name: "main"
        fields:
          - { label: "Title", name: "title
